### ISSUE TITLE
Add "change/show background" button for textures

### ISSUE THREAD

**Issue by CREEATION** [eiszfuchs/lo-rez-editor#3]
Handy for transparent textures.

**Comment by CREEATION** [comment]
Yes, I like this!

Is it possible to specify my own color instead of pink via colorpick in the future, maybe?

**Comment by eiszfuchs** [comment]
Why wait? 🎉 

![screen shot 2018-10-07 at 21 28 00](https://user-images.githubusercontent.com/240167/46585961-fda26f00-ca77-11e8-8e7c-d95e0c1aa39a.png)
